#!/usr/bin/env python3
"""Regenerate the switch registry from the sources.

    tools/mkswitches.py            # rewrite src/damswitch_list.h and docs/SWITCHES.md
    tools/mkswitches.py --check    # exit 1 if either is out of date

Every CCX_* name the binary reads is found by scanning for getenv in the C
and Fortran sources.  The generated header is what damswitch.c reports from,
so a run's log states its own configuration and a misspelt switch is named
instead of silently doing nothing - which is the failure that makes an A/B
uninformative rather than wrong, and therefore the expensive kind.
"""
import argparse,os,re,sys,collections

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC=os.path.join(ROOT,'src')
HDR=os.path.join(SRC,'damswitch_list.h')
DOC=os.path.join(ROOT,'docs','SWITCHES.md')
GETENV=re.compile(r'getenv\s*\(\s*[\'"](CCX_[A-Z0-9_]+)[\'"]')

def scan():
    where=collections.defaultdict(set)
    for dirpath,_,files in os.walk(SRC):
        for fn in sorted(files):
            if not fn.endswith(('.c','.f','.h')): continue
            if fn=='damswitch_list.h': continue
            txt=open(os.path.join(dirpath,fn),errors='replace').read()
            for m in GETENV.finditer(txt):
                where[m.group(1)].add(fn)
    return {k:sorted(v) for k,v in sorted(where.items())}

def docs_text():
    out=[]
    for dirpath,_,files in os.walk(ROOT):
        if '.git' in dirpath.split(os.sep): continue
        for fn in files:
            if fn.endswith('.md') and os.path.join(dirpath,fn)!=DOC:
                out.append(open(os.path.join(dirpath,fn),errors='replace').read())
    return '\n'.join(out)

def src_text():
    out=[]
    for dirpath,_,files in os.walk(SRC):
        for fn in files:
            if fn.endswith(('.c','.f','.h')) and fn!='damswitch_list.h':
                out.append(open(os.path.join(dirpath,fn),errors='replace').read())
    return '\n'.join(out)

def header(sw):
    L=["/* GENERATED by tools/mkswitches.py - do not edit.",
       "",
       "   Every CCX_* name this binary reads.  damswitch.c reports the ones",
       "   that are set and names anything else in the environment that looks",
       "   like one of ours, so a misspelt switch is caught on the spot rather",
       "   than quietly doing nothing.",
       "",
       "   Regenerate with tools/mkswitches.py; tools/mkswitches.py --check",
       "   fails if this file is stale. */",
       "",
       "#define DAMSWITCH_COUNT %d"%len(sw),
       "",
       "static const char *const damswitch_name[DAMSWITCH_COUNT]={"]
    for k in sw: L.append('  "%s",'%k)
    L+=["};",""]
    return "\n".join(L)

def document(sw,dtxt,stxt):
    known=set(sw)
    nd=[k for k in sw if k not in dtxt]
    L=["# Environment switches",
       "",
       "GENERATED by `tools/mkswitches.py` - do not edit by hand.",
       "",
       "| | |",
       "|---|---|",
       "| names the binary reads | **%d** |"%len(sw),
       "| mentioned in some other `.md` | %d |"%(len(sw)-len(nd)),
       "| **documented nowhere but here** | **%d** |"%len(nd),
       "",
       "Every run prints the ones that are set, and names anything in the",
       "environment starting with `CCX_` that is not in this list - see",
       "`[SWITCHES]` at the top of any `run.log`.",
       "",
       "| switch | read by | explained elsewhere |",
       "|---|---|---|"]
    for k in sw:
        L.append("| `%s` | %s | %s |"%(k,", ".join("`%s`"%f for f in sw[k]),
                                       "yes" if k in dtxt else "**no**"))
    L+=["",
        "\"explained elsewhere\" means the name appears in some other markdown",
        "file in this tree.  It is a presence check, not a quality one: a",
        "switch marked yes may still be described badly.  A switch marked no",
        "has nothing written about it anywhere except the line that reads it."]
    return "\n".join(L)+"\n"

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true')
    a=ap.parse_args()
    sw=scan(); h=header(sw); d=document(sw,docs_text(),src_text())
    if a.check:
        bad=[]
        for path,want in ((HDR,h),(DOC,d)):
            have=open(path).read() if os.path.exists(path) else None
            if have!=want: bad.append(path)
        if bad:
            print("stale, regenerate with tools/mkswitches.py:")
            for p in bad: print("  "+os.path.relpath(p,ROOT))
            return 1
        print("switch registry is up to date (%d switches)"%len(sw))
        return 0
    os.makedirs(os.path.dirname(DOC),exist_ok=True)
    open(HDR,'w').write(h); open(DOC,'w').write(d)
    print("wrote %s and %s: %d switches"%(os.path.relpath(HDR,ROOT),
                                          os.path.relpath(DOC,ROOT),len(sw)))
    return 0

if __name__=='__main__': sys.exit(main())
